wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 36
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 0.0002062038000611627
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 50
period_length:
  value: 19.45275059850248
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
