wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 25
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 0.001818990882201207
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 25
period_length:
  value: 46.49785189113118
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
