wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 49
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 0.00010047048344056975
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 29.1591760081722
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
