wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 25
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 1.578218052023409e-05
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 50
period_length:
  value: 23.19036233872562
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
