wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 16
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 0.0001436037229230776
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 25
period_length:
  value: 41.84919804624085
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
