wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 25
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 0.00010762256988262176
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 33.36366281434729
spatial_kernel:
  value: Matern
temporal_kernel:
  value: RBF
