wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 25
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 0.0003021744146260259
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 16.723405750339225
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
