wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 25
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: true
learning_rate:
  value: 0.006519915269957958
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 17.872280521233417
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
