wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 16
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: true
learning_rate:
  value: 3.525028591761101e-05
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 50
period_length:
  value: 32.501034552513616
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
