wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 16
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 1.0548418802394451e-05
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 25
period_length:
  value: 45.4164371961607
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
