wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 36
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 0.003616201906790101
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 50
period_length:
  value: 17.707463243184705
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
