wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 25
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 1.2206679438615646e-05
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 25
period_length:
  value: 42.98791491349963
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
