wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 16
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 9.039150872722356e-05
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 32.869460787049704
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
