wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 36
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 0.004348504451661667
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 25
period_length:
  value: 25.19756058725776
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
