wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 36
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 0.00015641433951502803
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 25
period_length:
  value: 26.841418341046214
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
