wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 36
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: true
learning_rate:
  value: 0.00017018912421768982
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 50
period_length:
  value: 13.28127732664934
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
