wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 25
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 5.352442387431145e-05
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 50
period_length:
  value: 41.825234300322606
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
