wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 16
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 0.0003099430290099027
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 22.076706686360193
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
