wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 36
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 9.475410788620571e-05
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 25
period_length:
  value: 15.98500714760462
spatial_kernel:
  value: Matern
temporal_kernel:
  value: RBF
