wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 49
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 0.000370373455031989
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 50
period_length:
  value: 46.18720664235163
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
