wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 25
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 0.001797937916393213
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 50
period_length:
  value: 12.691888299848037
spatial_kernel:
  value: Matern
temporal_kernel:
  value: RBF
