wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 25
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 0.0012916630516447687
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 25
period_length:
  value: 36.05548170588105
spatial_kernel:
  value: Matern
temporal_kernel:
  value: RBF
