wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 16
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 4.712995938429291e-05
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 17.98237649477491
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
