wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 36
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 1.0136641871309934e-05
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 25
period_length:
  value: 29.899116840216447
spatial_kernel:
  value: Matern
temporal_kernel:
  value: RBF
