wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 36
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 0.0002792263458042453
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 25
period_length:
  value: 21.392517776735065
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
