wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 49
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 0.00034136070524603965
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 25
period_length:
  value: 44.63153151823495
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
