wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 25
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 5.114150437500957e-05
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 25
period_length:
  value: 30.13750722184116
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
