wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 16
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 0.008621226944739418
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 50
period_length:
  value: 44.803630438961505
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
