wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 36
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 1.9650374817643933e-05
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 28.348500597059672
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
