wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 49
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 7.474222962318223e-05
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 34.13784163964371
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
