wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 25
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 0.00028268467674189457
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 29.192894189018094
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
