wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 16
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 0.00040330622289224343
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 33.68850996190794
spatial_kernel:
  value: Matern
temporal_kernel:
  value: RBF
