wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 49
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 3.487447360186335e-05
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 25
period_length:
  value: 12.142292310593326
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
