wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 49
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: true
learning_rate:
  value: 0.00019083196160412847
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 25
period_length:
  value: 42.072216624509615
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
