wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 25
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 5.156026111254789e-05
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 25
period_length:
  value: 44.93030759643141
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
