wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 16
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 0.0061324116707344506
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 25
period_length:
  value: 25.641770529783656
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
