wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 16
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 0.0007236518619894667
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 25
period_length:
  value: 19.782053223263738
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
