wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 36
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 0.0002024744020087546
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 25
period_length:
  value: 31.62027704307364
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
