wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 36
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 0.006541945111265047
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 25
period_length:
  value: 41.821107276445105
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
