wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 16
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 0.005995021351631991
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 25
period_length:
  value: 43.59682323277279
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
