wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 49
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 0.00020739799393125157
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 25
period_length:
  value: 15.454827246131854
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
