wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 49
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: true
learning_rate:
  value: 0.0013379000211130611
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 25
period_length:
  value: 37.343043566471216
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
