wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 49
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 1.0261961970239962e-05
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 39.30158549592085
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
