wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 49
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 0.0006877250020540834
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 25
period_length:
  value: 23.52369757302531
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
