wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 16
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: true
learning_rate:
  value: 3.760574338890705e-05
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 25
period_length:
  value: 40.11963793814775
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
