wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 49
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 2.4330344940329212e-05
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 50
period_length:
  value: 15.151648146228345
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
