wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 49
inducing_strategy:
  value: kmeans
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 4.540449073952355e-05
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 21.33318805279987
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
