wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 16
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 3.610939058639441e-05
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 25
period_length:
  value: 23.77211520296408
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
