wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 25
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: true
learning_rate:
  value: 5.287482574884278e-05
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 25
period_length:
  value: 36.53477108080943
spatial_kernel:
  value: Matern
temporal_kernel:
  value: RBF
