wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 16
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 0.003636976514070699
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 25
period_length:
  value: 33.11498239847636
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
