wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 25
inducing_strategy:
  value: grid
iterations:
  value: 200
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 4.6041795689522065e-05
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 25
period_length:
  value: 15.90204028923661
spatial_kernel:
  value: Matern
temporal_kernel:
  value: RBF
