wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 49
inducing_strategy:
  value: kmeans
iterations:
  value: 2000
kernel_combine:
  value: sum
learn_inducing:
  value: true
learning_rate:
  value: 0.0023237933062773483
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 42.04506356272475
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
