wandb_version: 1

batch_size:
  value: 256
grid_size:
  value: 36
inducing_strategy:
  value: grid
iterations:
  value: 2000
kernel_combine:
  value: sum
learn_inducing:
  value: true
learning_rate:
  value: 2.9017245353832205e-05
log_interval:
  value: 50
matern_nu:
  value: 1.5
patience:
  value: 50
period_length:
  value: 42.551247524667545
spatial_kernel:
  value: Matern
temporal_kernel:
  value: Periodic
