wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 36
inducing_strategy:
  value: kmeans
iterations:
  value: 2000
kernel_combine:
  value: product
learn_inducing:
  value: true
learning_rate:
  value: 0.0002989176103873608
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 50
period_length:
  value: 21.748211973828525
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
