_wandb:
    value:
        cli_version: 0.22.3
        e:
            d9zooyh5m2vr5ixegxbjpxdykw9zy4ye:
                args:
                    - --batch_size=1024
                    - --grid_size=25
                    - --inducing_strategy=grid
                    - --iterations=200
                    - --kernel_combine=sum
                    - --learn_inducing=True
                    - --learning_rate=0.00011406945782587046
                    - --log_interval=50
                    - --matern_nu=2.5
                    - --patience=50
                    - --period_length=20.322501684183376
                    - --spatial_kernel=RBF
                    - --temporal_kernel=Periodic
                codePath: analysis-modeling/wandb-experiments/run_experiment.py
                codePathLocal: run_experiment.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "589553541120"
                        used: "460201840640"
                email: njchandler2002@gmail.com
                executable: /storage/bln-aq/.venv/bin/python
                git:
                    commit: 68169003c70ca28d8a125693a01710ca06dd6623
                    remote: https://github.com/chandlerNick/bln-aq.git
                gpu: Tesla V100S-PCIE-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100S-PCIE-32GB
                      uuid: GPU-4d1c2617-649d-40f1-9430-2c9ab3297b79
                host: weatherts-6c75d475f6-lwbsc
                memory:
                    total: "540579323904"
                os: Linux-6.8.0-86-generic-x86_64-with-glibc2.36
                program: /storage/bln-aq/analysis-modeling/wandb-experiments/run_experiment.py
                python: CPython 3.11.9
                root: /storage/bln-aq/analysis-modeling/wandb-experiments
                startedAt: "2025-11-09T21:26:27.304731Z"
                writerId: d9zooyh5m2vr5ixegxbjpxdykw9zy4ye
        m:
            - "1": iteration
              "6":
                - 3
              "7": []
            - "1": train_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_rmse
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_rmse
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 53
                - 100
            "2":
                - 1
                - 5
                - 53
                - 100
            "3":
                - 2
                - 7
                - 14
                - 16
            "4": 3.11.9
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
batch_size:
    value: 1024
data_path:
    value: ../../data/2024-citsci-pollutants-hourly.parquet
grid_size:
    value: 25
inducing_strategy:
    value: grid
iterations:
    value: 200
kernel_combine:
    value: sum
learn_inducing:
    value: true
learning_rate:
    value: 0.00011406945782587046
log_interval:
    value: 50
lookback_days:
    value: 28
matern_nu:
    value: 2.5
patience:
    value: 50
period_length:
    value: 20.322501684183376
spatial_kernel:
    value: RBF
spatial_test_frac:
    value: 0.2
temp_horizon_hours:
    value: 1
temporal_kernel:
    value: Periodic
