wandb_version: 1

batch_size:
  value: 512
grid_size:
  value: 25
inducing_strategy:
  value: kmeans
iterations:
  value: 2000
kernel_combine:
  value: product
learn_inducing:
  value: false
learning_rate:
  value: 5.0189095541509515e-05
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 25
period_length:
  value: 33.943283733231965
spatial_kernel:
  value: RBF
temporal_kernel:
  value: Periodic
