wandb_version: 1

batch_size:
  value: 1024
grid_size:
  value: 49
inducing_strategy:
  value: kmeans
iterations:
  value: 2000
kernel_combine:
  value: sum
learn_inducing:
  value: false
learning_rate:
  value: 0.0002962044650996095
log_interval:
  value: 50
matern_nu:
  value: 2.5
patience:
  value: 25
period_length:
  value: 40.511900268125714
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
