_wandb:
    value:
        cli_version: 0.22.3
        e:
            b5wq1zob7oehycpcdyqmm4pciuxwbeyd:
                args:
                    - --batch_size=None
                    - --grid_size=25
                    - --inducing_strategy=kmeans
                    - --iterations=2000
                    - --kernel_combine=product
                    - --learn_inducing=True
                    - --learning_rate=0.000209009116533724
                    - --log_interval=50
                    - --matern_nu=0.5
                    - --patience=50
                    - --period_length=26.390136032482054
                    - --spatial_kernel=RBF
                    - --temporal_kernel=RBF
                codePath: analysis-modeling/wandb-experiments/run_experiment.py
                codePathLocal: run_experiment.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "589553541120"
                        used: "441591468032"
                email: njchandler2002@gmail.com
                executable: /storage/bln-aq/.venv/bin/python
                git:
                    commit: 44b2b921f7cc57197b93e2f6e5143220851e6868
                    remote: https://github.com/chandlerNick/bln-aq.git
                gpu: Tesla V100S-PCIE-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100S-PCIE-32GB
                      uuid: GPU-4d1c2617-649d-40f1-9430-2c9ab3297b79
                host: weatherts-6c75d475f6-75wz4
                memory:
                    total: "540579323904"
                os: Linux-6.8.0-86-generic-x86_64-with-glibc2.36
                program: /storage/bln-aq/analysis-modeling/wandb-experiments/run_experiment.py
                python: CPython 3.11.9
                root: /storage/bln-aq/analysis-modeling/wandb-experiments
                startedAt: "2025-11-08T13:44:20.429519Z"
                writerId: b5wq1zob7oehycpcdyqmm4pciuxwbeyd
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 53
                - 100
            "2":
                - 1
                - 5
                - 53
                - 100
            "3":
                - 14
                - 16
            "4": 3.11.9
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
batch_size:
    value: None
data_path:
    value: ../../data/2024-citsci-pollutants-hourly.parquet
grid_size:
    value: 25
inducing_strategy:
    value: kmeans
iterations:
    value: 2000
kernel_combine:
    value: product
learn_inducing:
    value: true
learning_rate:
    value: 0.000209009116533724
log_interval:
    value: 50
lookback_days:
    value: 28
matern_nu:
    value: 0.5
patience:
    value: 50
period_length:
    value: 26.390136032482054
spatial_kernel:
    value: RBF
spatial_test_frac:
    value: 0.2
temp_horizon_hours:
    value: 1
temporal_kernel:
    value: RBF
