wandb_version: 1

batch_size:
  value: None
grid_size:
  value: 36
inducing_strategy:
  value: kmeans
iterations:
  value: 2000
kernel_combine:
  value: sum
learn_inducing:
  value: true
learning_rate:
  value: 1.1643390898388548e-05
log_interval:
  value: 50
matern_nu:
  value: 0.5
patience:
  value: 25
period_length:
  value: 35.75319325663231
spatial_kernel:
  value: RBF
temporal_kernel:
  value: RBF
